const sidebars = {
  whitepaper: [
    {
      type: 'autogenerated',
      dirName: 'whitepaper',
    },
  ],
  techdocs: [
    {
      type: 'category',
      label: "What's OASYS?", 
      link: {
        type: 'doc',
        id: 'tech-docs/whats-oasys/1-1-whats-oasys',
      },
      collapsed: false,
      items: [
        {
          type: 'category',
          label: 'GameFi Chain', 
          link: {
            type: 'generated-index',
          },
          collapsed: false,
          items: [
            'tech-docs/whats-oasys/gamefi-chain/1-1-high-performance',
            'tech-docs/whats-oasys/gamefi-chain/1-2-decentralizaton-and-data-availability',
          ],
        },
        {
          type: 'category',
          label: 'What We Provide?', 
          link: {
            type: 'generated-index',
          },
          collapsed: false,
          items: [
            'tech-docs/whats-oasys/what-we-provide/1-1-private-as-public',
          ],
        },
        {
          type: 'category',
          label: 'Architecture', 
          link: {
            type: 'doc',
            id: 'tech-docs/whats-oasys/oasys-architecture/1-1-oasys-architecture',
          },
          collapsed: false,
          items: [
            'tech-docs/whats-oasys/oasys-architecture/1-2-original-rollup',
            'tech-docs/whats-oasys/oasys-architecture/1-3-incentive-logic',
          ],
        },
        {
          type: 'category',
          label: 'Roadmap', 
          link: {
            type: 'doc',
            id: 'tech-docs/whats-oasys/roadmap/1-1-initial-functionalities',
          },
          collapsed: false,
          items: [],
        }, 
      ],
    }
  ],
  architecture: [
    {
      type: 'category',
      label: 'Overview', 
      link: {
        type: 'generated-index',
      },
      collapsed: false,
      items: [
        {
          type: 'category',
          label: 'OASYS Architecture', 
          link: {
            type: 'generated-index',
          },
          collapsed: false,
          items: [
            'architecture/overview/oasys-architecture/1-1-ecosystem-per-chain',
            'architecture/overview/oasys-architecture/1-2-original-rollup',
            'architecture/overview/oasys-architecture/1-3-flexible-token-design',
          ]
        }, {
          type: 'category',
          label: 'Permissioned Chain', 
          link: {
            type: 'generated-index',
          },
          collapsed: false,
          items: [
            'architecture/overview/permissioned-chain/1-1-high-qualiry-database',
            // 'architecture/overview/permissioned-chain/1-2-efficient-load',
          ]
        }
      ]
    },
    {
      type: 'category',
      label: 'Hub Layer', 
      link: {
        type: 'generated-index',
      },
      collapsed: false,
      items: [
        {
          type: 'category',
          label: 'Consensus Algorithm', 
          link: {
            type: 'doc',
            id: 'architecture/hub-layer/consensus/1-1-hub-consensus',
          },
          collapsed: false,
          items: [
            {
              type: 'category',
              label: 'DPoS', 
              link: {
                type: 'generated-index',
              },
              collapsed: false,
              items: [
                'architecture/hub-layer/consensus/dpos/1-1-weighted-random',
                'architecture/hub-layer/consensus/dpos/1-2-mining',
              ]
            }, {
              type: 'category',
              label: 'Incentive Logic', 
              link: {
                type: 'generated-index',
              },
              collapsed: false,
              items: [
                'architecture/hub-layer/consensus/incentive/1-1-validator-staker',
                'architecture/hub-layer/consensus/incentive/1-2-reward-commission',
              ]
            }
          ]
        }, {
          type: 'category',
          label: 'OASYS Ecosystem', 
          link: {
            type: 'doc',
            id: 'architecture/hub-layer/ecosystem/1-1-ecosystem',
          },
          collapsed: false,
          items: [
            {
              type: 'category',
              label: 'Fungible Token', 
              link: {
                type: 'generated-index',
              },
              collapsed: false,
              items: [
                'architecture/hub-layer/ecosystem/ft/1-1-ft-types',
                'architecture/hub-layer/ecosystem/ft/1-2-bridge',
                'architecture/hub-layer/ecosystem/ft/1-3-dex',
                'architecture/hub-layer/ecosystem/ft/1-4-oas-tokens',
              ]
            }, {
              type: 'category',
              label: 'Non Fungible Token', 
              link: {
                type: 'doc',
                id: 'architecture/hub-layer/ecosystem/nft/1-1-nft-types',
              },
              collapsed: false,
              items: [
                'architecture/hub-layer/ecosystem/nft/1-1-nft-types',
                'architecture/hub-layer/ecosystem/nft/1-2-bridge',
                // 'architecture/hub-layer/ecosystem/nft/1-3-oasyx',
                'architecture/hub-layer/ecosystem/nft/1-4-marketplace',
              ]
            }
          ]
        }
      ]
    },
    {
      type: 'category',
      label: 'Verse Layer', 
      link: {
        type: 'doc',
        id: 'architecture/verse-layer/1-1-verse-layer'
      },
      collapsed: false,
      items: [
        {
          type: 'category',
          label: 'Verse Consensus (PoA or PoS)', 
          link: {
            type: 'doc',
            id: 'architecture/verse-layer/consensus/1-1-consensus'
          },
          collapsed: false,
          items: []
        }, {
          type: 'category',
          label: 'Permissioned / Permissionless', 
          link: {
            type: 'doc',
            id: 'architecture/verse-layer/permission/1-1-permission'
          },
          collapsed: false,
          items: []
        }, {
          type: 'category',
          label: 'Original Rollup', 
          link: {
            type: 'doc',
            id: 'architecture/verse-layer/rollup/1-1-overview'
          },
          collapsed: false,
          items: [
            'architecture/verse-layer/rollup/1-1-overview',
            'architecture/verse-layer/rollup/1-2-difference',
            {
              type: 'category',
              label: 'Verifier', 
              link: {
                type: 'doc',
                id: 'architecture/verse-layer/rollup/1-3-verifier'
              },
              collapsed: false,
              items: [
                'architecture/verse-layer/rollup/2-1-how-to-pay-network-fee',
                'architecture/verse-layer/rollup/2-2-initial-verifier',
              ]
            }
          ]
        }
      ]
    },
  ],
  hubvalidator: [
    {
      type: 'category',
      label: "Operate Validator", 
      link: {
        type: 'generated-index',
      },
      collapsed: false,
      items: [
        'hub-validator/operate-validator/1-1-hd-requirement',
        'hub-validator/operate-validator/1-2-build-validator-node',
        'hub-validator/operate-validator/1-3-join-validator-cli',
        'hub-validator/operate-validator/1-4-join-validator-web',
        'hub-validator/operate-validator/1-5-setup-verifier',
        'hub-validator/operate-validator/1-6-monitor',
      ]
    },
    {
      type: 'category',
      label: "Tools", 
      link: {
        type: 'generated-index',
      },
      collapsed: false,
      items: [
        'hub-validator/tools/2-1-hub-geth',
        'hub-validator/tools/2-2-oaspos'
      ]
    },
  ],
  versedeveloper: [
    {
      type: 'category',
      label: 'Intro', 
      link: {
        type: 'doc',
        id: 'verse-developer/1-1-select',
      },
      collapsed: false,
      items: [],
    },
    {
      type: 'category',
      label: "Build Verse", 
      link: {
        type: 'generated-index',
      },
      collapsed: false,
      items: [
        'verse-developer/how-to-build-verse/1-1-requirement',
        'verse-developer/how-to-build-verse/1-2-manual',
        'verse-developer/how-to-build-verse/1-3-optional-configs',
        'verse-developer/how-to-build-verse/1-4-verse-proxy',
        'verse-developer/how-to-build-verse/1-5-explore',
      ],
    },
    {
      type: 'category',
      label: "Tokens", 
      link: {
        type: 'generated-index',
      },
      collapsed: false,
      items: [
        'verse-developer/handle-token/1-1-vft',
        'verse-developer/handle-token/1-2-vnft',
        'verse-developer/handle-token/1-3-oft',
        'verse-developer/handle-token/1-4-onft',
      ],
    },
    {
      type: 'category',
      label: "Game",
      link: {
        type: 'doc',
        id: 'verse-developer/game/1-1'
      },
      collapsed: false,
      items: [
        {
          type: 'category',
          label: "Tutorial", 
          link: {
            type: 'generated-index',
          },
          collapsed: false,
          items: [
            'verse-developer/game/tutorial/1-1',
            'verse-developer/game/tutorial/1-2',
          ],
        },
        {
          type: 'category',
          label: "Repository", 
          link: {
            type: 'generated-index',
          },
          collapsed: false,
          items: [
            'verse-developer/game/repository/1-1',
            'verse-developer/game/repository/1-2',
            'verse-developer/game/repository/1-3',
            'verse-developer/game/repository/1-4',
          ],
        },
        {
          type: 'category',
          label: "Function", 
          link: {
            type: 'generated-index',
          },
          collapsed: false,
          items: [
            'verse-developer/game/blockchain-functionality/1-1',
            'verse-developer/game/blockchain-functionality/1-2',
            'verse-developer/game/blockchain-functionality/1-3',
            'verse-developer/game/blockchain-functionality/1-4',
          ],
        },
        {
          type: 'category',
          label: "NFT Creation", 
          link: {
            type: 'generated-index',
          },
          collapsed: false,
          items: [
            'verse-developer/game/nft-creation/1-1',
            'verse-developer/game/nft-creation/1-2',
            'verse-developer/game/nft-creation/1-3',
            'verse-developer/game/nft-creation/1-4',
          ],
        },
      ],
    },
    {
      type: 'category',
      label: 'oFT/oNFT Bridge', 
      link: {
        type: 'doc',
        id: 'verse-developer/1-2-bridge-between-verses',
      },
      collapsed: false,
      items: [],
    },
  ],
  staking: [
    {
      type: 'category',
      label: "Staking", 
      link: {
        type: 'generated-index',
      },
      collapsed: false,
      items: [
        'staking/stake-oasys/1-1-stake-oasys',
        'staking/stake-oasys/1-2-stake-cli',
      ],
    },
    {
      type: 'category',
      label: 'Setup Metamask', 
      link: {
        type: 'doc',
        id: 'staking/setup-metamask/1-1-how-to-setup',
      },
      collapsed: false,
      items: [],
    },
    {
      type: 'category',
      label: 'RPC Endpoint', 
      link: {
        type: 'doc',
        id: 'staking/rpc-endpoint/1-1-rpc-endpoint',
      },
      collapsed: false,
      items: [],
    },
    {
      type: 'category',
      label: 'Official Links', 
      link: {
        type: 'doc',
        id: 'staking/official-links/1-1-official-links',
      },
      collapsed: false,
      items: [],
    },
  ],
  devtools: [
    {
      type: 'autogenerated',
      dirName: 'dev-tools',
    },
  ],
};
module.exports = sidebars;